name: Upload AWS Control Statuses to ServiceNow

on:
  schedule:
    - cron: '0 13 * * *'   # 8am Central (UTC-5); does not adjust for DST
  workflow_dispatch:     # manual trigger optional

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      SN_I: ${{ secrets.SN_I }}
      SN_T: ${{ secrets.SN_T }}
      SN_U: ${{ secrets.SN_U }}
      SN_P: ${{ secrets.SN_P }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          pip install -r requirements.txt

      - name: Run sync script
        run:
          python main.py
